# ufunc

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5])
v


array([1, 2, 3, 4, 5])

In [3]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [4]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [5]:
np.multiply(v, 5)

array([ 5, 10, 15, 20, 25])

In [6]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [7]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [8]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [9]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [10]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [11]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [12]:
np.absolute(np.array([-5]))

array([5])

In [13]:
np.sin(360)

0.9589157234143065

In [14]:
np.cos(180)

-0.5984600690578581

In [15]:
v = np.array([1, 2, 3])

In [16]:
np.log2(v)

array([0.       , 1.       , 1.5849625])