# Processing subsets

In [1]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[8, 1, 4, 1, 9],
       [5, 9, 4, 5, 2],
       [7, 9, 2, 8, 8],
       [0, 3, 3, 0, 6],
       [4, 0, 2, 0, 2]])

In [2]:
subset_a = a[0:3, 0:2]
subset_a

array([[8, 1],
       [5, 9],
       [7, 9]])

In [3]:
subset_a[0, 0] = 999
subset_a[1, 1] = 888

In [4]:
subset_a

array([[999,   1],
       [  5, 888],
       [  7,   9]])

In [5]:
a

array([[999,   1,   4,   1,   9],
       [  5, 888,   4,   5,   2],
       [  7,   9,   2,   8,   8],
       [  0,   3,   3,   0,   6],
       [  4,   0,   2,   0,   2]])

### If you do not want to make changes to the original array

In [6]:
m = np.random.randint(10, size = (5, 5))
m

array([[2, 3, 8, 5, 6],
       [8, 0, 7, 8, 5],
       [3, 4, 2, 7, 4],
       [0, 9, 2, 5, 9],
       [9, 1, 8, 6, 1]])

In [7]:
subset_b = m[0:3, 0:2].copy()
subset_b

array([[2, 3],
       [8, 0],
       [3, 4]])

In [8]:
subset_b[0,0] = 999

In [9]:
subset_b

array([[999,   3],
       [  8,   0],
       [  3,   4]])

In [10]:
m

array([[2, 3, 8, 5, 6],
       [8, 0, 7, 8, 5],
       [3, 4, 2, 7, 4],
       [0, 9, 2, 5, 9],
       [9, 1, 8, 6, 1]])