# Accessing to element with Fancy Index

In [1]:
import numpy as np

v = np.arange(0, 30, 3)

v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
v[1]

3

In [3]:
v[3]

9

In [4]:
[v[1], v[3]]

[3, 9]

In [5]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [6]:
get = [1, 3, 5]

In [7]:
v[get]

array([ 3,  9, 15])

### Two dimension fancy

In [8]:
m = np.arange(9).reshape(3, 3)

In [9]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
line = np.array([0, 1])

In [11]:
column = np.array([1, 2])

In [12]:
m[line, column]

array([1, 5])

In [13]:
n = np.arange(15).reshape(3,5)

In [14]:
n

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
n[2, [3, 4]] # third line,  fourth and fifth element

array([13, 14])