# Splitting

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 42, 34, 67, 99, 12])

In [3]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([42, 34]), array([67, 99, 12])]

In [4]:
a, b, c = np.split(x, [3, 5])

In [5]:
a

array([1, 2, 3])

In [6]:
b

array([42, 34])

In [7]:
c

array([67, 99, 12])

In [8]:
m = np.arange(16).reshape(4, 4)

In [9]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [11]:
top, bottom = np.vsplit(m, [2])

In [12]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
bottom

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [15]:
right, left = np.hsplit(m, [2])

In [16]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [17]:
left

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])