* creating array with numpy functions

In [1]:
import numpy as np

In [2]:
np.zeros(10,dtype=int) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.full((3,5),3,dtype = float)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [4]:
np.arange(0,31,3) 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [5]:
np.linspace(0,1,10) 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.random.normal(10,4,(3,4))

array([[ 5.83599052,  8.52169178, 16.2644546 ,  7.95592645],
       [11.40520413,  9.95042742, 11.5830486 ,  8.90171939],
       [16.05145302, 10.18180282, 11.60033636,  8.14000381]])

In [7]:
np.random.randint(0, 10, (3, 3))

array([[5, 3, 7],
       [0, 8, 7],
       [3, 6, 3]])

In [8]:
np.random.randint(0,10,(3,3))

array([[1, 4, 1],
       [4, 1, 5],
       [5, 0, 5]])