# Access to element with slicing

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
a[2::3]

array([22, 25, 28])

# Multidimensions slice process
### Usage : 
#### arrayName[ row:row_end, column:column_end ]

In [8]:
m = np.random.randint(10, size = (5,5))

In [9]:
m

array([[2, 1, 4, 3, 2],
       [9, 0, 6, 0, 8],
       [8, 4, 6, 9, 7],
       [1, 8, 3, 7, 8],
       [3, 4, 6, 1, 8]])

In [10]:
m[:,0] # select all rows and print zero column

array([2, 9, 8, 1, 3])

In [11]:
m[:,1]

array([1, 0, 4, 8, 4])

In [12]:
m[:,3]

array([3, 0, 9, 7, 1])

In [13]:
m[0,:]

array([2, 1, 4, 3, 2])

In [14]:
m[0]

array([2, 1, 4, 3, 2])

In [15]:
m[1,:]

array([9, 0, 6, 0, 8])

In [16]:
m[0:2, 0:3]

array([[2, 1, 4],
       [9, 0, 6]])