# Sorting

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,5,7,3,4,6])

In [3]:
v

array([2, 1, 5, 7, 3, 4, 6])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
v

array([2, 1, 5, 7, 3, 4, 6])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5, 6, 7])

#### two dimension

In [8]:
m = np.random.normal(20, 5, (3,3))

In [9]:
m

array([[24.33931436, 17.74334213, 18.22362083],
       [12.37307965, 18.48550716, 15.08875555],
       [21.59451148, 27.28298926, 20.71224298]])

In [10]:
np.sort(m, axis = 1)

array([[17.74334213, 18.22362083, 24.33931436],
       [12.37307965, 15.08875555, 18.48550716],
       [20.71224298, 21.59451148, 27.28298926]])

In [11]:
np.sort(m, axis = 0)

array([[12.37307965, 17.74334213, 15.08875555],
       [21.59451148, 18.48550716, 18.22362083],
       [24.33931436, 27.28298926, 20.71224298]])